# Generated by Django 5.0.3 on 2025-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
